### ISSUE TITLE
Build issues on Arch Linux

### ISSUE THREAD

**Issue by Gilah-EnE** [bootchk/resynthesizer#100]
I tried to install the plugin from GitHub using the official instructions, `autogen.sh` worked fine, but `make` did not compile it. I'm using GIMP 2.10.24 from official repos. Here is my output:

> LANG=en_US make
make  all-recursive
make[1]: Entering directory '/home/gilah/resynthesizer'
Making all in lib
make[2]: Entering directory '/home/gilah/resynthesizer/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/gilah/resynthesizer/lib'
Making all in src
make[2]: Entering directory '/home/gilah/resynthesizer/src'
Making all in resynthesizer
make[3]: Entering directory '/home/gilah/resynthesizer/src/resynthesizer'
gcc  -g -O2 -Wall   -o resynthesizer resynthesizer-resynthesizer.o -lglib-2.0 -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -lm -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -ljson-glib-1.0 -lbabl-0.1 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype  ../../lib/libresynthesizer.a -lm -lgthread-2.0 -lgthread-2.0 
/usr/bin/ld: ../../lib/libresynthesizer.a(libresynthesizer_a-engine.o): in function `orderTargetPointsRandom':
engine.c:(.text+0xcf4): undefined reference to `swap_vector_elements'
/usr/bin/ld: ../../lib/libresynthesizer.a(libresynthesizer_a-engine.o): in function `randomizeBandsTargetPoints':
engine.c:(.text+0xdd7): undefined reference to `swap_vector_elements'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:402: resynthesizer] Error 1
make[3]: Leaving directory '/home/gilah/resynthesizer/src/resynthesizer'
make[2]: *** [Makefile:351: all-recursive] Error 1
make[2]: Leaving directory '/home/gilah/resynthesizer/src'
make[1]: *** [Makefile:405: all-recursive] Error 1
make[1]: Leaving directory '/home/gilah/resynthesizer'
make: *** [Makefile:346: all] Error 2

**Comment by bootchk** [comment]
Thanks for reporting.  For now, I don't have time to fix it properly.  All I can do is offer my thoughts...

The problem is in the "engine" library.  It compiles on other  platforms. The undefined reference is all internal to the library (it is not a reference to  a function defined in another library.)  To explore the issue, get on GitHub and search for "swap_vector_elements."  That undefined reference is to the inlined function swap_vector_elements defined in lib/engineTypes.h which is included by other source files of the library.  I suspect the problem is related to the inlining: the compiler inlines the function at some places where it is called, and does NOT inline it at other places where it is called, leaving it as an undefined symbol to be resolved at link time, but also fails to define a symbol for the function when it is not inlined, so the link time resolution fails.   I am not blaming the compiler, it may be something I don't understand about "inlining" in C compilers.  Which as I recall, in some compilers is a pragma, which can be ignored by the compiler.

You might be able to work around by turning off optimization (don't use -O2) ?

Exactly which Arch version and gcc version are you using?  

If I find time to explore further, I would first replicate your environment and try your exact sequence of compile steps.  But I use "vagga" to create containerized dev environments, and it doesn't seem to support installing Arch Linux in a container.  The best I could probably do would be to test under Ubuntu, but use the specific compiler version that you are using.

**Comment by Gilah-EnE** [comment]
> Could you try changing the definition "inline swap_vector_elements" to "static inline swap_vector_elements "

Thanks, that fixed the issue; it built great, but I was trying on another machine, and there weren't any problems. I'm closing this issue.

> Exactly which Arch version and gcc version are you using?

AFAIK, the current GCC version (11.1.0), was flagged out-of-date on 2021-07-28, much earlier than the issue date. Nevertheless, there's no problems now, but still very strange why they were. Arch Linux is rolling-release, there's no versions/
