### ISSUE TITLE
Compiling Resynthesizer v2.0

### ISSUE THREAD

**Issue by KasimAhmic** [bootchk/resynthesizer#28]
I took some time and compiled Resynthesizer on my Ubuntu VM, transferred the Python files over to Windows, put them in the appropriate directory, and tried them out. When comparing it to the 1.0 files, there seems to be no clear speed increase. Looking at my Task Manager, the CPU usage and clock speed also seem about the same. The only thing I can think of that might be causing this is me compiling it incorrectly. I followed the instructions listed in the REAMDE.md file.

What exactly could I be doing wrong?

**Comment by bootchk** [comment]
You might be compiling correctly, there is no guarantee it will be much faster.  I assume you have multiple cores and are expecting threading to speed it up.  Even with say 8 cores, it might be only twice as fast since the threading occurs not at the top of the algorithm, but say midway down the algorithm chain (the algorithm makes many passes through an image, and each pass, the image is broken into subareas for processing by threads.)

I don't understand why you mentioned Ubuntu AND Windows, are you cross-compiling?

**Comment by KasimAhmic** [comment]
Oh ok, I understand. Yes I have a quad core processor and yeah I just assumed that the entire algorithm would be split up between the cores and speed up the overall processing. As for why I mentioned both Ubuntu and Windows, I figured that me compiling Resynthesizer on Ubuntu and using the files on Windows could have been causing the issue. I figured so cause I thought I read something about the files not compiling or installing correctly if compiled in Windows.

Thanks for the reply,
Kasim Ahmić
