### ISSUE TITLE
New release with new tarball

### ISSUE THREAD

**Issue by Beep6581** [bootchk/resynthesizer#33]
Hello

Please make a new release with a new tarball so that distros will agree to pick it up - they are lax when it comes to shipping git snapshots.

**Comment by bootchk** [comment]
You mean a new tagged version?  Also, there is no tarball under version control, only the one that github rolls on demand.  I would be glad to help if I understood the process.

AFAIK, only Redhat distro might be distributing it (since they opened an issue about a missing file they needed.)  I know that at one time Debian was distributing it, but I don't know the current status.

**Comment by Beep6581** [comment]
Releases are tied to tags, this page explains how to make them:
https://help.github.com/articles/creating-releases/

The latest tag/release you have is from 2012 and some distros are very stubborn about shipping only officially released versions, so it would be nice if you released a 2016 version :)

Do you run the http://www.logarithmic.net/pfh/resynthesizer website? It would be great if you could add dates to releases, as it is quite difficult to figure our for example when version 0.16 was released. I mention 0.16 because that is the latest version in Gentoo, and it appears to be from 2008 :/

**Comment by bootchk** [comment]
Thanks for explaining.  I will work on it.  Although the only changes since 2012 have been changes to support building and distribution!  E.g. the latest commit was for Redhat, apparently they and others are developing a process so that scattered plugins can be distributed more reliably.

How will any distro (say Gentoo) discover that my repo should be distributed?  I.e. is there a nominating process?

No I don't run the original website, it belongs to the original author of resynthesizer.

No, not aware of that website.  I used to follow gimp dev and gegl dev mailing lists, and have struggled to find an appropriate website.

**Comment by Beep6581** [comment]
I will open an issue in Gentoo's bug tracker to update the "ebuild" using the new release on github as a source:
http://bugs.gentoo.org/

So the original website is essentially dead?

If you want to get resynthesizer working with GIMP git master (2.9.*) and perhaps even shipped with it, then joining http://discuss.pixls.us/ could be a good idea, as would opening an issue it GIMP's bug tracker https://bugzilla.gnome.org/ and joining IRC to talk with the developers https://www.gimp.org/irc.html

**Comment by bootchk** [comment]
OK, done, see 2.0.1

Original website may be maintained for other purposes, but original author is NOT maintaining Resynthesizer and is aware that I am and links to my repo.

There is an open issue to port Resynthesizer to a GEGL plugin.  The problem is that unlike most GIMP plugins, it is a lot of code.  Also, it does not follow GIMP coding standards.  Also, unlike many 'filter' plugins, it needs access to the entire image at once, instead of raster scanning via tiles.  So first to GEGL, and then think about whether GIMP org wants to distribute.

Also, as you may be aware, there are other 'inpainting' implementations, such as in G'Mic and OpenCV.

**Comment by Beep6581** [comment]
Thank you, I posted about updating Gentoo's Resynthesizer ebuild:
https://bugs.gentoo.org/show_bug.cgi?id=364619

**Comment by bootchk** [comment]
Thanks for sharing.  And for stepping up as build maintainer in Gentoo.  Once I considered taking over Debian build maintainer but it is daunting.  Good luck, and don't hesitate to ask.
