### ISSUE TITLE
Not working anymore on GIMP 2.9

### ISSUE THREAD

**Issue by IvanDSM** [bootchk/resynthesizer#35]
Trying to use "Heal selection" or any other resynthesizer module results in the following error under GIMP 2.9:

"WARNING: Plug-In "plugin-heal-selection.py"
(/usr/lib/gimp/2.0/plug-ins/plugin-heal-selection.py)
called deprecated procedure 'gimp-selection-combine'.
It should call 'gimp-image-select-item' instead!"

**Comment by bootchk** [comment]
When was 2.9 released?  Just because a function is deprecated does not mean it is an error to call it: that is a non-fatal warning that in the future the function will become "obsolete" and removed from the GIMP library.  Thanks for reporting, but I hope it is a spurious report.   I have not been following new releases of GIMP so it is possible the Resynthesizer is broken with a new release.

**Comment by bootchk** [comment]
Which version (with three numerals), e.g. 2.9.4?   Did the plugin fail to have the desired effect?  Was the warning message in a dialog that interrupted your work flow, or was it in on a console window where you started GIMP?  I think there is a "Preferences" or some other way to suppress such warning dialogs, if it was a dialog?  Unfortunately, I think most plugin developers consider such warnings a nuisance that is best fixed by users changing the Preference, rather than by fixing the code.  I am vague because it has been a while since I looked at the problem of warnings for deprecated functions.

**Comment by bootchk** [comment]
OK.  I have found other reports of this, and a patch, on the web.  I think it is a fix to the Python component of the plugin.  I will fix it soon.  Thanks for reporting it.

**Comment by IvanDSM** [comment]
I apologize for not having responded earlier, I was away from the computer. I am using GIMP 2.9.5. I noticed that while "Heal selection" kind of works (gives bad results), the main Resynthesizer command gives some very weird results. Selecting certain kinds of objects enlarges them (sometimes very realistically, sometimes very glitchy).

**Comment by bootchk** [comment]
Oh, thats another matter.  2.9.5 is the next release?  I will look into it, and thanks.

**Comment by bootchk** [comment]
2.9.5 is an unstable development release.  The GIMP project turns on the reported warnings in such a release.  This issue was reported, and a pull request that fixes it was submitted, earlier.  I will apply the pull request the next time there is a significant change to Resynthesizer, or when GIMP actually obsoletes the deprecated API.  Otherwise, any changes to Resynthesizer might trigger upstream builds for an issue that only affects users who are using an unstable development release of GIMP.

**Comment by johnnybex** [comment]
I have accidentally created this same error when trying to use "Heal selection" in Gimp 2.9.5. and the operation failed.  This was when I had just created a layer mask between 2 copies of the same image and I realised that I had not subsequently merged the 2 copies.  I tried "Heal selection" again after the images were merged and all was well

**Comment by bootchk** [comment]
v2.0.3 fixes the warning about deprecated functions.
