### ISSUE TITLE
map-style issue

### ISSUE THREAD

**Issue by dafrasaga** [bootchk/resynthesizer#43]
Hi,
when I perform map-style on gimp 2.9.5 I have this error:

Traceback (most recent call last):
  File "/usr/local/lib/gimp/2.0/python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "/usr/local/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/usr/local/lib/gimp/2.0/plug-ins/plugin-map-style.py", line 280, in transfer_style
    if original_source_base_type == INDEXED :
NameError: global name 'INDEXED' is not defined

Plug-in "plugin-map-style.py"
(/usr/local/lib/gimp/2.0/plug-ins/plugin-map-style.py)
called deprecated procedure 'gimp-drawable-get-image'.
It should call 'gimp-item-get-image' instead!

Any hints??
Cheers
Gabriele

**Comment by bootchk** [comment]
Off the top of my head, INDEXED should be defined by PyGimp.  So that is very strange.  I will need to try to replicate it.

 I think the two messages are unrelated.  The other message is usually when someone is using a beta release of gimp, where they don't allow the use of deprecated functions.  There is a work around, discussed in other issues on this repository.  But you say you are using 2.9.5, which is not a developer's release?

**Comment by dafrasaga** [comment]
Hi, I use gimp-cce which is 2.9.5 but it is not a stabile release.
Cheers
Il 30/set/2017 17:17 "Lloyd Konneker" <notifications@github.com> ha scritto:

**Comment by bootchk** [comment]
I think gimp-cce is a fork of GIMP, and not a stable release.  Thus this issue probably does not concern most users, so I am closing it.
