### ISSUE TITLE
Can't install Resynthesizer on Ubuntu 18.04 Gimp 2.10.6

### ISSUE THREAD

**Issue by hannonq** [bootchk/resynthesizer#57]
Hi, I'm trying to install the package using the commands from the readme, but when I run `./autogen.sh` I get the error 

> configure: error: GIMP development libraries not found; please install.

I installed GIMP using the otto-kesselgulasch/gimp repository. Could that be the problem?

I have already (successfully) installed the dependencies mentioned in the build chain section. 

A few things I have tried after some googling (I'm not sure if these tries are actually related to ho to solve this problem, but I'll share it anyway).
1. `apt-get install gimp-plugin-registry` gives the error

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  gimp-plugin-registry : Depends: gimp (>= 2.6) but it is not going to be installed
>                         Recommends: gimp-gmic
> E: Unable to correct problems, you have held broken packages.

2. `apt-get install gimp`

> gimp is already the newest version (2.10.6+om-0ubu18.04.2~ppa)

3. `snap install gimp`

> snap "gimp" is already installed, see 'snap help refresh'

EDIT 1:

4. `apt-get install libgimp2.0-dev`

> libgimp2.0-dev is already the newest version (2.10.6+om-0ubu18.04.2~ppa).

Any ideas?
Thanks!

**Comment by bootchk** [comment]
This error message =>  configure: error: GIMP development libraries not found; please install.
usually means that this package was not installed   => libgimp2.0-dev

To clarify the discussion, you seem to be "building" the resynthesizer from the source obtained from this github repository.  The resynthesizer is not actually "packaged" on this repository, since a package is usually ready to be installed without building.  To build the resynthesizer, you must first install many build tools (compilers etc.), and install the header files for the libraries that the resynthesizer must be built with (compiled and linked with.)  Said header files for libraries are usually packaged separately from packages that contain the library.  In this case, the library is libgimp (generically, with a version number it is named something like libgimp-2.0).    It is not enough to install the package that contains the GIMP application; that installs the library but not the header files needed for development (to build a plugin such as the resynthesizer.)  You must also install the so-called "GIMP development package" that includes the header files for the library libgimp.  In this case, said development package is usually named "libgimp2.0-dev".  So you usually need "apt-get install libgimp2.0-dev"  before you start building resynthesizer.

I could be wrong, names and packaging might have changed, that is all off the top of my head and could have typos, and I have not recently built resynthesizer for 18.04.

**Comment by hannonq** [comment]
Thanks for you quick reply, @bootchk 
However,  libgimp2.0-dev appears to already be installed. When I run "apt-get install libgimp2.0-dev", I get

>  libgimp2.0-dev is already the newest version (2.10.6+om-0ubu18.04.2~ppa).

Can you think of any other package that I am missing?

**Comment by bootchk** [comment]
I am still exploring.  An update on lack of progress: 

 I read the configure.ac script.  You can see there where the error message is delivered, apparently when libgimp-2.0 or libgimpui-2.0 is not present according to the package manager?  I have only limited knowledge of these scripts, the tools they call, and the libraries they are looking for, since the scripts were written by the GIMP project and I just made a few modifications.  

I also see that GIMP 2.10.6 was released very recently, so I am wondering whether something has changed by the GIMP org.

It might be that no one else has built resynthesizer for GIMP v2.10.6 yet.  This repository is set up to build automatically on Travis CI, but I just looked, it only builds when there is a commit to this repository, so it hasn't built in 4 months.   I also don't know which GIMP release Travis builds against.

Also, to answer your question, libglib2.0-dev is another required package (for a library), but that is noted in the readme, and I assume you have checked that.

**Comment by bootchk** [comment]
Also, in my opinion, you have complicated the install process.  It might work better if you stick to Ubuntu packages for GIMP and plugins (gimp-plugin-registry), if you don't need the very latest GIMP (I don't know what GIMP version that Ubuntu 18.04 delivers, probably not GIMP 2.10.6.)

You say you have installed a GIMP 2.10.6 from another ppa. I would guess that does not overwrite any GIMP packages installed from Ubuntu releases, and that might be the problem, i.e. some sort of problem where the build of resynthesizer is looking at two different GIMP installations, roughly speaking.

I also see that you have tried snap.  At least to me, that also is bleeding edge.  I myself am just learning about snap and app image and flatpack: all competing technologies for easing installation, with no consensus in the community, yet.  See https://askubuntu.com/questions/866511/what-are-the-differences-between-snaps-appimage-flatpak-and-others

There are other issues reported for resynthesizer and other third party plugins about the flatpack distribution of GIMP.  I hope to resolve that issue (create scripts to build the resynthesizer as a flatpack.)  But now I see that would only help some users, those who use flatpack instead of snap or app image.  So I am waiting for a consensus to build.

**Comment by hannonq** [comment]
Again, thank you for your detailed reasoning about this problem. I haven't had time to try anything else yet, but as soon as possible I'll try a fresh install of GIMP using the Ubuntu packages. I indeed don't necessarily need the very latest GIMP version. I'll let you know if it works, and also if it doesn't.

**Comment by hannonq** [comment]
@bootchk , I've finally been able to install the package, but I can't get GIMP to show the plugin options on the interface.

I did many things to try to install it, and what I **think** that fixed my problem was:
Completely remove GIMP and the packages below:
```
sudo apt-get remove --purge gimp  
sudo apt-get remove --purge libgimp2.0-dev libpcre3-dev  
sudo apt-get autoremove  
```
I also disabled the otto-kesselgulasch/gimp ppa.

Then:
```
sudo apt-get update  
sudp apt-get upgrade  
sudo apt-get install gimp  
sudo apt-get install libgimp2.0-dev libpcre3-dev  
```

This time, GIMP 2.10.6 was installed straight from Ubuntu repository. I was surprised to see that Ubuntu is up to date with the latest version of a package, for a change.

After having done that, I was able to run the install commands from the root directory downloaded from this repository:

```
./autogen.sh  
./configure   
make  
make install
```

I needed to run `make install` as sudo in order to have access to the `/usr/local/lib/` folder. 

So, everything was installed smoothly, but I still can't access the Enhance>Heal selection (or any other tools) from GIMP.

In my `/usr/lib/gimp/2.0/plug-ins` folder I see the following:

```
...  
-rwxr-xr-x 1 root root 165088 Oct 14 15:50 resynthesizer  
-rwxr-xr-x 1 root root  82728 Oct 14 15:50 resynthesizer_gui  
...  
```

And I have also set the path as per readme:

> Installs to the shared Gimp directories. Except on Ubuntu, it installs to /usr/local/lib/gimp/2.0/plug-ins and you may need to set the GIMP Edit>Preferences>Folders>Plugins> to include that path.

After restarting GIMP, I still can't see the filters :/

Any ideas?

**Comment by lapega** [comment]
> This time, GIMP 2.10.6 was installed straight from Ubuntu repository. I was surprised to see that Ubuntu is up to date with the latest version of a package, for a change.

Are you sure? I followed your steps, and after remove Otto ppa, Ubuntu offers to install gimp 2.8
(I have ubuntu 18.04).

**Comment by mak-bd** [comment]
it is not installing in ubuntu 18.04 with ppa build, 
copying py file can not create resynth engine, may only get some interface.
some body need to amend the configure file.

**Comment by bootchk** [comment]
Closing this issue since it might be two problems: 1) building GIMP and resynthesizer from ppa's in advance of a distribution release, and 2) installing resynthesizer into an installed snap of GIMP.  The former is often  "you are on your own" since too many things can go wrong.  The latter problem remains to be fixed.

I recently added vagga scripts, and used those to test that resynthesizer builds on Ubuntu 18.10 and 19.04 with GIMP and GIMP libraries that Ubuntu packaged with those distributions.  The documented build process and dependencies appear to remain correct.
