### ISSUE TITLE
Heal selection not healing the entire selection

### ISSUE THREAD

**Issue by jluttine** [bootchk/resynthesizer#63]
Thanks for this amazing tool! I'm trying to heal selections but no matter what options I choose, only some portion of the selection gets healed.

Here's a screenshot after healing the selection (the black area + 10px growth):

![image](https://user-images.githubusercontent.com/2195834/56894408-73127300-6a8e-11e9-8744-26b0f8f44e74.png)

Visible healing has happened only here and there near the selection edges, maybe 10-100px from the selection edge. Most of the selected black area remains black. Why? Am i doing something wrong?

**Comment by jluttine** [comment]
I'm using this via GIMP Filters -> Enhance -> Heal selection.

**Comment by bootchk** [comment]
My initial thought is that the black area is actually transparent to a black background, i.e. it is not a natural, original image and someone has doctored it already.  Resynthesizer "heal selection" won't change total transparency.  You could try "Heal transparency."  Or maybe flatten the image you have already healed (since the colors might be there, just not visible when transparency is enabled.)  I could be wrong, these are just my preliminary thoughts, I have not opened your image, and I would like to have the image in a format that includes transparency (and I can't remember whether .png would.)  If this suggestion does not help, please get back to me.

**Comment by jluttine** [comment]
Thanks for the quick response! There's not alpha channel nor transparency, it's just a regular JPG file. "Heal transparency" option is disabled, probably because there's no transparency.

Here is the original image file (not a screenshot):

![IMGP5908 - IMGP5944](https://user-images.githubusercontent.com/2195834/56898831-b07cfd80-6a9a-11e9-9a92-3d3e12d1ef57.jpg)

**Comment by bootchk** [comment]
Thanks for persevering with me while I think out loud.  My next guess is to try healing in the inwards direction (one of the choices.)

Also, I see that the lower right corner is black also.  You might try healing that first, from a source (context) which is just the clouds.  Although that should not make a difference if the "context width" choice is relatively small, say 50.  In that case, it should try to heal from a stone-colored ring around your black hole  (is that what you intended?)

But if you were trying to heal with a large context width (say 400) then it would try to heal from say every other pixel in your image, and might surreptitiously (in a bad sense, what is the word for that?) start healing some pixel from a black pixel in the lower right, and proceed to grow that black pixel.

If you tried to heal both areas at once, I am not sure that would give you your desired result either.  

I am just guessing at what your desired result is.  If you desire anything other than a "plausible" stone colored center, I doubt that resynthesizer is up to the job.  But I agree with you, I would have guessed it would create a stone colored center instead of a black hole.

Rotation and perspective is not handled well by resynthesizer.  E.g. it might put that stone tower in the upper right of the healing, and it would look strange.

**Comment by jluttine** [comment]
I tried all directions (random, inwards, outwards) and always similar result. I tried very small context width and large context width, always similar result: the majority of the hole always stayed black.

I've had this similar problem with very small holes too. It just changes the shape of the black hole a little bit, never filling it.

And yes, I don't know how good the filling will look, but at least I'd get something to start with. Probably requires more effort to make it look realistic. For now, I'd just like the whole black area to be healed.

**Comment by bootchk** [comment]
Unfortunately, not reproducible here.  I opened the posted image (5.6M jpg), lassoed the black hole and tried Heal Selection three times with various parameters, for example, the defaults, and all tries healed the black hole, plausibly at least.

Are you sure that in the image you are working with has no other layers, especially an alpha layer?  I know that the image you posted was jpg.  Maybe try starting with a copy of the image you posted.  I am suggesting is that whatever export you used makes a difference, e.g. flattened the image.

Did you lasso, or create the selection in several steps?

I don't think the platform or version of GIMP and plugin should matter, except if you are using the  most recent, say the unreleased nightly build, of GIMP.  Then something might be broken, but I don't have any reason to think so.

**Comment by bootchk** [comment]
I assume this is resolved.

**Comment by jluttine** [comment]
Sorry for the delay, but this isn't working for me. Any ideas how I could debug in more detail?

The image has only one layer (I flattened the image), it has no alpha channel (I used the above jpg from this issue). I've used selection in two different ways: 1) by color & 10px growth, 2) with free-select tool around the hole.

**Comment by jluttine** [comment]
I launched gimp from terminal to see if it prints out something useful. Nope, nothing.

**Comment by jluttine** [comment]
Wait, I found something that might be relevant:

```
$ gimp
GIMP-Warning: Bad interpreter referenced in interpreter file /nix/store/7biympgqvvqwn026rbqyf2i9c281cz23-gimp-with-plugins-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp: python2

GIMP-Warning: Bad binary format string in interpreter file /nix/store/7biympgqvvqwn026rbqyf2i9c281cz23-gimp-with-plugins-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp

Plug-in "resynth"
(/nix/store/7biympgqvvqwn026rbqyf2i9c281cz23-gimp-with-plugins-2.10.10/lib/gimp/2.0/plug-ins/resynth) is installing procedure "plug-in-resynthesizer" with a full menu path "<Image>/Filters/Map/Resynthesize..." as menu label, this deprecated and will be an error in GIMP 3.0
```

**Comment by bootchk** [comment]
OK.  I see that you are using GIMP 2.10.10.   I will probably test that version.  If that doesn't reproduce, I may ask you to send me the file.  Sorry if I closed issue prematurely.

**Comment by bootchk** [comment]
Unable to reproduce.  Thus I would need to know more details:  what platform, OS version, Gimp version, resynthesizer version, how you installed gimp and the resynthesizer.

For example, in my test:  Linux, Ubuntu 16.04, Gimp 2.10.10, resynthesizer 2.0.3 (actually I built branch falseColorMatch, not master).  I downloaded, installed, and ran Gimp 2.10.10 using flatpak.  I built resynthesizer from a clone of the repository.  I installed it by copying the plugins to ~/.config/GIMP/2.0/plug-ins.  I tested using the .jpg that you posted.

**Comment by jtojnar** [comment]
This is what I get with your image + fuzzy select black centre + grow 10 px + heal selection:

![image](https://user-images.githubusercontent.com/705123/57290748-5c879f80-70be-11e9-9450-2a7bcd3a6b9c.png)

Console:

```
GIMP-Warning: Bad interpreter referenced in interpreter file /nix/store/487qbinai9yavyy1zazxwpnxs8w02lrl-gimp-with-plugins-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp: python2

GIMP-Warning: Bad binary format string in interpreter file /nix/store/487qbinai9yavyy1zazxwpnxs8w02lrl-gimp-with-plugins-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp

GeglBuffer* gimp_pickable_contiguous_region_by_seed(GimpPickable*, gboolean, gfloat, gboolean, GimpSelectCriterion, gboolean, gint, gint): foo took 0.0264 seconds
Gimp adaption
GeglBuffer* gimp_pickable_contiguous_region_by_seed(GimpPickable*, gboolean, gfloat, gboolean, GimpSelectCriterion, gboolean, gint, gint): foo took 0.0001 seconds
/nix/store/487qbinai9yavyy1zazxwpnxs8w02lrl-gimp-with-plugins-2.10.10/bin/.gimp-2.10-wrapped_: GEGL-WARNING: (gegl-tile-handler-cache.c:1075):gegl_tile_cache_destroy: runtime check failed: (g_queue_is_empty (&cache_queue))
EEEEeEeek! 1 GeglBuffers leaked
```

**Comment by jtojnar** [comment]
> ```
> GIMP-Warning: Bad interpreter referenced in interpreter file /nix/store/487qbinai9yavyy1zazxwpnxs8w02lrl-gimp-with-plugins-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp: python2
> 
> GIMP-Warning: Bad binary format string in interpreter file /nix/store/487qbinai9yavyy1zazxwpnxs8w02lrl-gimp-with-plugins-2.10.10/lib/gimp/2.0/interpreters/pygimp.interp
> 
> GeglBuffer* gimp_pickable_contiguous_region_by_seed(GimpPickable*, gboolean, gfloat, gboolean, GimpSelectCriterion, gboolean, gint, gint): foo took 0.0264 seconds
> Gimp adaption
> GeglBuffer* gimp_pickable_contiguous_region_by_seed(GimpPickable*, gboolean, gfloat, gboolean, GimpSelectCriterion, gboolean, gint, gint): foo took 0.0001 seconds
> /nix/store/487qbinai9yavyy1zazxwpnxs8w02lrl-gimp-with-plugins-2.10.10/bin/.gimp-2.10-wrapped_: GEGL-WARNING: (gegl-tile-handler-cache.c:1075):gegl_tile_cache_destroy: runtime check failed: (g_queue_is_empty (&cache_queue))
> EEEEeEeek! 1 GeglBuffers leaked
> ```

Wait, are you using `gimpPlugins.resynthesizer` instead of `gimpPlugins.resynthesizer2` (this repo)? I see that error message for resynthesiser 0.16 and do not even see the heal action in the menu.

**Comment by jtojnar** [comment]
Also know that resynthesizer2 did not work in nixpkgs until a few days ago: https://github.com/NixOS/nixpkgs/pull/60905

**Comment by bootchk** [comment]
If you are using version 0.16, that would explain the symptoms.  That is the original code, it had bugs (with same symptoms) fixed by versions 1 and 2, many years ago.

jtojnar: thanks for your help.   Glad you are distributing resynthesizer for NixOS.  I am overwhelmed by the flux in Linux distribution, e.g. I am studying flatpak now since gimp.org seems to be leaning that way, but I am not sure it  is the answer.  I also dabble with vagga (userspace containers for developers.)  NixOS seems a great idea.

**Comment by jluttine** [comment]
Ok, thanks to both of you! I had all Gimp plugins installed. Indeed, removing `gimpPlugins.resynthesizer` and thus forcing `gimpPlugins.resynthesizer2` instead fixed the issue. So it was probably using version 0.16 earlier. I couldn't verify this though because I couldn't figure out a way to see plugin version numbers inside Gimp. But sorry for bothering!

However, related to NixOS, why do we even have version 0.16 there?? I installed `gimp-with-plugins` so that I get all plugins, and apparently what I got was this wrong version of resynthesizer. Would be nice if at least in that case it would install the newer version. I couldn't figure out an easy way to install all plugins except resynthesizer 0.16. But this is NixOS stuff, I can open an issue for that in nixpkgs, or what are your thoughts @jtojnar?

**Comment by jtojnar** [comment]
Apparently, the 0.16 still works, it is just in `Filters/Map/Resynthesize`. We should figure out how to make the `resynthesizer2` command not trigger the `resynthesizer0.16` commands.

**Comment by bootchk** [comment]
I do not think you should distribute any component of v0.16.  As I said, it had bugs fixed in later versions.  

The later versions do not discard any functionality.  I think the only reason to distribute v0.16 would be to support users who do not want to install PyGimp, since the user facing plugins in v0.16 were written in Scheme.  Without dredging through the history, I can't recall whether the bugs were fixed in the engine (the .c plugin) or in the user facing plugins (.scm) or both.  It is conceivable you could use the user facing plugins (.scm) of v0.16 with the engine (.c plugin-resythnesizer?) of v2, since the ABI of the engine has not changed.  But I strongly advise against it, unless you test it thoroughly.

**Comment by jtojnar** [comment]
Thanks for explaining. Since you are saying it does have any extra features, I will just drop it. We already require Python with GIMP so limiting to scheme was not useful.

**Comment by jtojnar** [comment]
Reportedly, there was a feature set change https://github.com/NixOS/nixpkgs/pull/61365#issuecomment-491604698
