### ISSUE TITLE
error: procedure not found: pdb.plug_in_resynthesizer in snap version of GIMP on Ubuntu 20.04

### ISSUE THREAD

**Issue by strexgth** [bootchk/resynthesizer#87]
As I was about to use the heal selection plug-in, it gave me the following error: Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/home/favour/snap/gimp/322/.config/GIMP/2.10/plug-ins/plugin-heal-selection.py", line 148, in heal_selection
    pdb.plug_in_resynthesizer(timg, tdrawable, 0,0, useBorder, work_drawable.ID, -1, -1, 0.0, 0.117, 16, 500)
error: procedure not found

Can someone please help with this? I am currently using Linux, ubuntu 20.04.

**Comment by wesbz** [comment]
:+1:  I encounter the same issue!

**Comment by strexgth** [comment]
> 👍 I encounter the same issue!

Have you been able to find a fix for this issue?

**Comment by bootchk** [comment]
I assume you got the resynthesizer from some other place, because Ubuntu 20.04 does not package it anymore.  I also assume you got the snap packaged GIMP which seems to have the package gimp-python (a Python2 especially for GIMP, since many distributions don't package Python 2, anymore, not supported by the python org as of Jan. 2020.)

I am guessing that when you installed resynthesizer, you omitted a step:  copy the executable file "resynthesizer" to the plugins directory.  That file is the "engine" plugin that also registers itself as a plugin in the PDB, and that the Python plugins such as "heal selection" call.  Thats what the error message means to me.

**Comment by strexgth** [comment]
I downloaded GIMP through the software manager, and I installed the resynthesizer plugin from GitHub, and extracted them to my download folder, dragged the python files to my Gimp plugin folder and made them executable. I later got the error message once I tried to run the plugin.

**Comment by bootchk** [comment]
It will not work to  copy just the Python plugins from the resynthesizer repository clone.
You need to "build" the repository clone.
A "build" compiles an executable plugin file called "resynthesizer."
Then you need to install/copy that file, as well as the Python plugins.
